#!/usr/bin/env node
'use strict';

const readline    = require('readline');
const fs          = require('fs');
const path        = require('path');
const os          = require('os');
const { execSync } = require('child_process');

const PLUGIN_ROOT = process.env.CLAUDE_PLUGIN_ROOT || path.resolve(__dirname, '..');

const SKILLS = ['pge', 'pge-strict', 'pge-quality', 'pge-ultra', 'pge-idontcaretokenanymore', 'pge-god', 'pge-update', 'pge-autolaunch'];
const AGENTS = [
  'planner', 'generator', 'evaluator',
  'evaluator-standard', 'evaluator-strict', 'evaluator-quality', 'evaluator-godmode',
  'pge-orchestrator',
];

// ── Paths ─────────────────────────────────────────────────────────────────────
const CLAUDE_DIR    = path.join(os.homedir(), '.claude');
const COMMANDS_DIR  = path.join(CLAUDE_DIR, 'commands');
const AGENTS_DIR    = path.join(CLAUDE_DIR, 'agents');
const HOOKS_DIR     = path.join(CLAUDE_DIR, 'hooks');
const SETTINGS_FILE = path.join(CLAUDE_DIR, 'settings.json');
const HOOK_FILE     = path.join(HOOKS_DIR, 'pge-autolaunch.sh');

// ── Install skills + agents ───────────────────────────────────────────────────
function install() {
  fs.mkdirSync(COMMANDS_DIR, { recursive: true });
  fs.mkdirSync(AGENTS_DIR,   { recursive: true });
  fs.mkdirSync(HOOKS_DIR,    { recursive: true });

  for (const skill of SKILLS) {
    const src  = path.join(PLUGIN_ROOT, 'skills', skill, 'SKILL.md');
    const dest = path.join(COMMANDS_DIR, `${skill}.md`);
    if (fs.existsSync(src)) fs.copyFileSync(src, dest);
  }

  for (const agent of AGENTS) {
    const src  = path.join(PLUGIN_ROOT, 'agents', `${agent}.md`);
    const dest = path.join(AGENTS_DIR, `${agent}.md`);
    if (fs.existsSync(src)) {
      if (fs.existsSync(dest)) fs.copyFileSync(dest, `${dest}.bak`);
      fs.copyFileSync(src, dest);
    }
  }

  // Write hook script with correct PLUGIN_ROOT
  const hookContent = `#!/bin/bash
# Auto-generated by PGE Orchestrator MCP server — do not edit manually.
# Re-runs on every plugin update to keep PLUGIN_ROOT current.

INPUT=$(cat)
PROMPT=$(echo "$INPUT" | jq -r '.prompt // ""' 2>/dev/null)

if ! echo "$PROMPT" | grep -qE '^\\s*/(pge|pge-strict|pge-quality|pge-ultra|pge-idontcaretokenanymore|pge-god|pge-orchestrator)(\\s|$)'; then
  exit 0
fi

CWD=$(echo "$INPUT" | jq -r '.cwd // ""' 2>/dev/null)
[ -z "$CWD" ] && CWD="$PWD"

PGE_PLUGIN="${PLUGIN_ROOT}"
INDICATOR="$PGE_PLUGIN/bridge/pge-indicator.cjs"
NOTIFY="$PGE_PLUGIN/bridge/pge-notify.cjs"

osascript 2>/dev/null <<APPLESCRIPT
tell application "Terminal"
  activate
  do script "node '$INDICATOR' '$CWD'; echo ''; echo '[PGE] Pipeline ended. Press any key to close.'; read -n1"
end tell
APPLESCRIPT

node "$NOTIFY" "$CWD" > /dev/null 2>&1 &
exit 0
`;
  fs.writeFileSync(HOOK_FILE, hookContent, { mode: 0o755 });
}

// ── Settings helpers ──────────────────────────────────────────────────────────
function readSettings() {
  try { return JSON.parse(fs.readFileSync(SETTINGS_FILE, 'utf8')); }
  catch { return {}; }
}

function writeSettings(s) {
  fs.writeFileSync(SETTINGS_FILE, JSON.stringify(s, null, 2));
}

const HOOK_CMD = `bash "${HOOK_FILE}"`;

function isAutolaunchEnabled(s) {
  return (s?.hooks?.UserPromptSubmit || [])
    .some(h => h.hooks?.some(hk => hk.command === HOOK_CMD));
}

function autolaunchOn() {
  const s = readSettings();
  if (isAutolaunchEnabled(s)) return 'Auto-launch is already enabled.';
  if (!s.hooks) s.hooks = {};
  if (!s.hooks.UserPromptSubmit) s.hooks.UserPromptSubmit = [];
  s.hooks.UserPromptSubmit.push({ hooks: [{ type: 'command', command: HOOK_CMD, async: true }] });
  writeSettings(s);
  return 'Auto-launch enabled. Restart Claude Code to apply.';
}

function autolaunchOff() {
  const s = readSettings();
  if (!s?.hooks?.UserPromptSubmit) return 'Auto-launch is already disabled.';
  s.hooks.UserPromptSubmit = s.hooks.UserPromptSubmit.filter(
    h => !h.hooks?.some(hk => hk.command === HOOK_CMD)
  );
  writeSettings(s);
  return 'Auto-launch disabled. Restart Claude Code to apply.';
}

// ── Update ────────────────────────────────────────────────────────────────────
function update() {
  const isGit = fs.existsSync(path.join(PLUGIN_ROOT, '.git'));
  if (!isGit) return 'Plugin directory is not a git repo. Cannot auto-update.';

  let pkgBefore = '?';
  try { pkgBefore = JSON.parse(fs.readFileSync(path.join(PLUGIN_ROOT, '.claude-plugin', 'plugin.json'), 'utf8')).version; } catch {}

  let pullOut;
  try {
    pullOut = execSync('git pull --ff-only origin main', { cwd: PLUGIN_ROOT, stdio: 'pipe' }).toString().trim();
  } catch (e) {
    return `git pull failed: ${e.message}`;
  }

  install(); // re-install after pull

  let pkgAfter = '?';
  try { pkgAfter = JSON.parse(fs.readFileSync(path.join(PLUGIN_ROOT, '.claude-plugin', 'plugin.json'), 'utf8')).version; } catch {}

  const changed = pkgBefore !== pkgAfter ? `${pkgBefore} → ${pkgAfter}` : `${pkgAfter} (no version change)`;
  const alreadyUpToDate = pullOut.includes('Already up to date');

  return [
    alreadyUpToDate ? 'Already up to date.' : pullOut,
    `Version: ${changed}`,
    'Skills and agents reinstalled.',
    'Restart Claude Code to apply changes.',
  ].join('\n');
}

// ── Status ────────────────────────────────────────────────────────────────────
function status() {
  const installedSkills = SKILLS.filter(s => fs.existsSync(path.join(COMMANDS_DIR, `${s}.md`)));
  const installedAgents = AGENTS.filter(a => fs.existsSync(path.join(AGENTS_DIR, `${a}.md`)));
  const autolaunch      = isAutolaunchEnabled(readSettings());
  return [
    `PGE Orchestrator`,
    `Plugin root : ${PLUGIN_ROOT}`,
    `Skills  (${installedSkills.length}/${SKILLS.length}): ${installedSkills.join(', ') || 'none'}`,
    `Agents  (${installedAgents.length}/${AGENTS.length}): ${installedAgents.join(', ') || 'none'}`,
    `Auto-launch : ${autolaunch ? 'enabled' : 'disabled'}`,
  ].join('\n');
}

// ── MCP server ────────────────────────────────────────────────────────────────
function send(obj) { process.stdout.write(JSON.stringify(obj) + '\n'); }

const TOOLS = [
  {
    name: 'pge_status',
    description: 'Show PGE Orchestrator installation status and auto-launch state.',
    inputSchema: { type: 'object', properties: {}, required: [] },
  },
  {
    name: 'pge_update',
    description: 'Update PGE Orchestrator: git pull + reinstall all skills and agents.',
    inputSchema: { type: 'object', properties: {}, required: [] },
  },
  {
    name: 'pge_autolaunch_on',
    description: 'Enable auto-launch: opens indicator terminal when /pge is invoked.',
    inputSchema: { type: 'object', properties: {}, required: [] },
  },
  {
    name: 'pge_autolaunch_off',
    description: 'Disable auto-launch for PGE terminal indicator.',
    inputSchema: { type: 'object', properties: {}, required: [] },
  },
];

const rl = readline.createInterface({ input: process.stdin, terminal: false });

rl.on('line', (line) => {
  let msg;
  try { msg = JSON.parse(line.trim()); } catch { return; }
  if (!msg || msg.jsonrpc !== '2.0') return;

  const { id, method } = msg;

  if (method === 'initialize') {
    try { install(); } catch {}
    send({
      jsonrpc: '2.0', id,
      result: {
        protocolVersion: '2024-11-05',
        capabilities: { tools: {} },
        serverInfo: { name: 'pge-orchestrator', version: '2.5.0' },
      },
    });

  } else if (method === 'notifications/initialized') {
    // no response for notifications

  } else if (method === 'tools/list') {
    send({ jsonrpc: '2.0', id, result: { tools: TOOLS } });

  } else if (method === 'tools/call') {
    const name = msg.params?.name;
    let text;
    try {
      if (name === 'pge_status')          text = status();
      else if (name === 'pge_update')     text = update();
      else if (name === 'pge_autolaunch_on')  text = autolaunchOn();
      else if (name === 'pge_autolaunch_off') text = autolaunchOff();
      else text = `Unknown tool: ${name}`;
    } catch (e) {
      text = `Error: ${e.message}`;
    }
    send({ jsonrpc: '2.0', id, result: { content: [{ type: 'text', text }] } });

  } else if (id !== undefined) {
    send({ jsonrpc: '2.0', id, result: {} });
  }
});
