#!/usr/bin/env node
'use strict';

const readline     = require('readline');
const fs           = require('fs');
const path         = require('path');
const os           = require('os');
const { execSync, execFileSync, spawnSync } = require('child_process');

const PLUGIN_ROOT = process.env.CLAUDE_PLUGIN_ROOT || path.resolve(__dirname, '..');

const SKILLS = [
  'pge', 'pge-strict', 'pge-quality', 'pge-ultra',
  'pge-idontcaretokenanymore', 'pge-god',
  'pge-update', 'pge-autolaunch',
  'pge-statusline', 'pge-preflight', 'pge-clean', 'pge-summary',
  'pge-indicator', 'pge-notify', 'pge-eval-backend',
  'pge-limit',
];
const AGENTS = [
  'planner', 'generator', 'evaluator',
  'evaluator-standard', 'evaluator-strict', 'evaluator-quality', 'evaluator-godmode',
  'evaluator-codex', 'evaluator-gemini',
  'pge-orchestrator',
];

// ── Paths ─────────────────────────────────────────────────────────────────────
const CLAUDE_DIR    = path.join(os.homedir(), '.claude');
const COMMANDS_DIR  = path.join(CLAUDE_DIR, 'commands');
const AGENTS_DIR    = path.join(CLAUDE_DIR, 'agents');
const HOOKS_DIR     = path.join(CLAUDE_DIR, 'hooks');
const HUD_DIR       = path.join(CLAUDE_DIR, 'hud');
const SETTINGS_FILE = path.join(CLAUDE_DIR, 'settings.json');
const HOOK_FILE     = path.join(HOOKS_DIR, 'pge-autolaunch.sh');
const COMBINED_SL   = path.join(HUD_DIR, 'pge-combined-statusline.sh');

const BRIDGE = (name) => path.join(PLUGIN_ROOT, 'bridge', `${name}.cjs`);

// ── Install ───────────────────────────────────────────────────────────────────
function install() {
  for (const d of [COMMANDS_DIR, AGENTS_DIR, HOOKS_DIR, HUD_DIR])
    fs.mkdirSync(d, { recursive: true });

  for (const skill of SKILLS) {
    const src = path.join(PLUGIN_ROOT, 'skills', skill, 'SKILL.md');
    if (fs.existsSync(src)) fs.copyFileSync(src, path.join(COMMANDS_DIR, `${skill}.md`));
  }

  for (const agent of AGENTS) {
    const src  = path.join(PLUGIN_ROOT, 'agents', `${agent}.md`);
    const dest = path.join(AGENTS_DIR, `${agent}.md`);
    if (fs.existsSync(src)) {
      if (fs.existsSync(dest)) fs.copyFileSync(dest, `${dest}.bak`);
      fs.copyFileSync(src, dest);
    }
  }

  // Write hook script (PLUGIN_ROOT baked in at install time)
  fs.writeFileSync(HOOK_FILE, `#!/bin/bash
# Auto-generated by PGE Orchestrator MCP server — do not edit manually.
INPUT=$(cat)
PROMPT=$(echo "$INPUT" | jq -r '.prompt // ""' 2>/dev/null)
if ! echo "$PROMPT" | grep -qE '^\\s*/(pge|pge-strict|pge-quality|pge-ultra|pge-idontcaretokenanymore|pge-god|pge-orchestrator)(\\s|$)'; then
  exit 0
fi
CWD=$(echo "$INPUT" | jq -r '.cwd // ""' 2>/dev/null)
[ -z "$CWD" ] && CWD="$PWD"
PGE_PLUGIN="${PLUGIN_ROOT}"
osascript 2>/dev/null <<APPLESCRIPT
tell application "Terminal"
  activate
  do script "node '$PGE_PLUGIN/bridge/pge-indicator.cjs' '$CWD'; echo ''; echo '[PGE] Pipeline ended. Press any key.'; read -n1"
end tell
APPLESCRIPT
node "$PGE_PLUGIN/bridge/pge-notify.cjs" "$CWD" > /dev/null 2>&1 &
exit 0
`, { mode: 0o755 });
}

// ── Settings helpers ──────────────────────────────────────────────────────────
function readSettings() {
  try { return JSON.parse(fs.readFileSync(SETTINGS_FILE, 'utf8')); }
  catch { return {}; }
}
function writeSettings(s) {
  fs.writeFileSync(SETTINGS_FILE, JSON.stringify(s, null, 2));
}

const HOOK_CMD = `bash "${HOOK_FILE}"`;
const SL_CMD   = `bash "${COMBINED_SL}"`;
const SL_SOLO  = `node "${BRIDGE('pge-statusline')}"`;

function isAutolaunchEnabled(s) {
  return (s?.hooks?.UserPromptSubmit || [])
    .some(h => h.hooks?.some(hk => hk.command === HOOK_CMD));
}

// ── Autolaunch on/off ─────────────────────────────────────────────────────────
function autolaunchOn() {
  const s = readSettings();
  if (isAutolaunchEnabled(s)) return 'Auto-launch is already enabled.';
  if (!s.hooks) s.hooks = {};
  if (!s.hooks.UserPromptSubmit) s.hooks.UserPromptSubmit = [];
  s.hooks.UserPromptSubmit.push({ hooks: [{ type: 'command', command: HOOK_CMD, async: true }] });
  writeSettings(s);
  return 'Auto-launch enabled. Restart Claude Code to apply.';
}
function autolaunchOff() {
  const s = readSettings();
  if (!isAutolaunchEnabled(s)) return 'Auto-launch is already disabled.';
  s.hooks.UserPromptSubmit = s.hooks.UserPromptSubmit.filter(
    h => !h.hooks?.some(hk => hk.command === HOOK_CMD));
  writeSettings(s);
  return 'Auto-launch disabled. Restart Claude Code to apply.';
}

// ── Status line on/off ────────────────────────────────────────────────────────
function statuslineOn() {
  const s = readSettings();
  const cur = s?.statusLine?.command || '';

  if (cur === SL_CMD || cur === SL_SOLO) return 'PGE status line is already enabled.';

  if (cur && cur !== SL_SOLO) {
    // Combine with existing status line
    fs.writeFileSync(COMBINED_SL, `#!/bin/bash
EXISTING=$(${cur} 2>/dev/null)
PGE=$(node "${BRIDGE('pge-statusline')}" 2>/dev/null)
if [ -n "$EXISTING" ] && [ -n "$PGE" ]; then printf '%s  ·  %s' "$EXISTING" "$PGE"
elif [ -n "$PGE" ]; then printf '%s' "$PGE"
else printf '%s' "$EXISTING"; fi
`, { mode: 0o755 });
    s.statusLine = { type: 'command', command: SL_CMD };
  } else {
    s.statusLine = { type: 'command', command: SL_SOLO };
  }

  writeSettings(s);
  return `PGE status line enabled. Restart Claude Code to apply.\nCommand: ${s.statusLine.command}`;
}
function statuslineOff() {
  const s = readSettings();
  const cur = s?.statusLine?.command || '';
  if (cur !== SL_CMD && cur !== SL_SOLO) return 'PGE status line is not currently set.';

  if (cur === SL_CMD) {
    // Try to extract the original command from combined script
    try {
      const txt = fs.readFileSync(COMBINED_SL, 'utf8');
      const m = txt.match(/^EXISTING=\$\((.+?) 2>\/dev\/null\)/m);
      if (m) { s.statusLine = { type: 'command', command: m[1] }; }
      else delete s.statusLine;
    } catch { delete s.statusLine; }
  } else {
    delete s.statusLine;
  }

  writeSettings(s);
  return 'PGE status line disabled. Restart Claude Code to apply.';
}

// ── Update ────────────────────────────────────────────────────────────────────
function update() {
  if (!fs.existsSync(path.join(PLUGIN_ROOT, '.git')))
    return 'Plugin directory is not a git repo. Cannot auto-update.';
  let before = '?';
  try { before = JSON.parse(fs.readFileSync(path.join(PLUGIN_ROOT, '.claude-plugin', 'plugin.json'), 'utf8')).version; } catch {}
  let pullOut;
  try { pullOut = execSync('git pull --ff-only origin main', { cwd: PLUGIN_ROOT, stdio: 'pipe' }).toString().trim(); }
  catch (e) { return `git pull failed: ${e.message}`; }
  install();
  let after = '?';
  try { after = JSON.parse(fs.readFileSync(path.join(PLUGIN_ROOT, '.claude-plugin', 'plugin.json'), 'utf8')).version; } catch {}
  return [
    pullOut.includes('Already up to date') ? 'Already up to date.' : pullOut,
    `Version: ${before !== after ? `${before} → ${after}` : `${after} (unchanged)`}`,
    'Skills and agents reinstalled. Restart Claude Code to apply.',
  ].join('\n');
}

// ── Preflight ─────────────────────────────────────────────────────────────────
function preflight(cwd) {
  const r = spawnSync('node', [BRIDGE('pge-preflight')], { cwd: cwd || process.cwd(), encoding: 'utf8' });
  return (r.stdout + r.stderr).replace(/\x1b\[[0-9;]*m/g, '').trim();
}

// ── Clean ─────────────────────────────────────────────────────────────────────
function clean(cwd) {
  const r = spawnSync('node', [BRIDGE('pge-clean'), '--force'], { cwd: cwd || process.cwd(), encoding: 'utf8' });
  return (r.stdout + r.stderr).replace(/\x1b\[[0-9;]*m/g, '').trim();
}

// ── Summary ───────────────────────────────────────────────────────────────────
function summary(cwd) {
  const r = spawnSync('node', [BRIDGE('pge-summary'), cwd || process.cwd()], { encoding: 'utf8' });
  return (r.stdout + r.stderr).replace(/\x1b\[[0-9;]*m/g, '').trim();
}

// ── Open indicator terminal ───────────────────────────────────────────────────
function openIndicator(cwd) {
  const dir = cwd || process.cwd();
  execSync(`osascript -e 'tell application "Terminal" to do script "node \\"${BRIDGE('pge-indicator')}\\" \\"${dir}\\"; read -n1"'`);
  return `Indicator terminal opened for: ${dir}`;
}

// ── Eval backend ─────────────────────────────────────────────────────────────
function evalBackend(action, backend, isGlobal, cwd) {
  const args = ['node', BRIDGE('pge-eval-backend')];
  if (action === 'set' && backend) {
    args.push('set', backend);
    if (isGlobal) args.push('--global');
  } else if (action === 'clear') {
    args.push('clear');
  } else {
    args.push('show');
  }
  if (cwd) args.push(cwd);
  const [cmd, ...rest] = args;
  const r = spawnSync(cmd, rest, { cwd: cwd || process.cwd(), encoding: 'utf8' });
  return (r.stdout + r.stderr).trim();
}

// ── Start notify ──────────────────────────────────────────────────────────────
function startNotify(cwd) {
  const dir = cwd || process.cwd();
  const r = spawnSync('node', [BRIDGE('pge-notify'), dir], {
    detached: true, stdio: 'ignore',
  });
  return `Notification watcher started for: ${dir}`;
}

// ── Status ────────────────────────────────────────────────────────────────────
function status() {
  const s = readSettings();
  const slCmd = s?.statusLine?.command || '';
  const slEnabled = slCmd === SL_CMD || slCmd === SL_SOLO;
  const installedSkills = SKILLS.filter(sk => fs.existsSync(path.join(COMMANDS_DIR, `${sk}.md`)));
  const installedAgents = AGENTS.filter(a  => fs.existsSync(path.join(AGENTS_DIR,   `${a}.md`)));

  // Read active eval backend (project or global)
  let evalBackendVal = 'claude (default)';
  const projCfg = path.join(process.cwd(), 'pge-workspace', '.eval-backend');
  const globalCfg = path.join(os.homedir(), '.claude', 'pge-eval-backend');
  try {
    if (fs.existsSync(projCfg))   evalBackendVal = fs.readFileSync(projCfg, 'utf8').trim() + ' (project)';
    else if (fs.existsSync(globalCfg)) evalBackendVal = fs.readFileSync(globalCfg, 'utf8').trim() + ' (global)';
  } catch {}

  return [
    `PGE Orchestrator v2.7.0`,
    `Plugin root  : ${PLUGIN_ROOT}`,
    `Skills  (${installedSkills.length}/${SKILLS.length}): ${installedSkills.join(', ') || 'none'}`,
    `Agents  (${installedAgents.length}/${AGENTS.length}): ${installedAgents.join(', ') || 'none'}`,
    `Auto-launch  : ${isAutolaunchEnabled(s) ? 'enabled' : 'disabled'}`,
    `Status line  : ${slEnabled ? 'enabled' : 'disabled'}`,
    `Eval backend : ${evalBackendVal}`,
  ].join('\n');
}

// ── Usage limit guard ─────────────────────────────────────────────────────────
const LIMIT_CONFIG_PATH = path.join(os.homedir(), '.claude', 'pge-limit-config.json');
const GUARD_PID_FILE    = '/tmp/pge-usage-guard.pid';

function setLimit({ threshold, type = '5h', maxTokens = null, cwd }) {
  const cfg = {
    threshold : Number(threshold),
    type,
    maxTokens : maxTokens ? Number(maxTokens) : null,
    enabled   : true,
    setAt     : new Date().toISOString(),
  };
  fs.writeFileSync(LIMIT_CONFIG_PATH, JSON.stringify(cfg, null, 2));

  // Kill any previous guard
  try {
    const pid = Number(fs.readFileSync(GUARD_PID_FILE, 'utf8').trim());
    if (pid) process.kill(pid, 0) && process.kill(pid, 'SIGTERM');
  } catch {}

  // Start new guard in background
  const { spawn } = require('child_process');
  const guard = spawn(
    process.execPath,
    [BRIDGE('pge-usage-guard'), cwd || process.cwd()],
    { detached: true, stdio: 'ignore' },
  );
  guard.unref();

  const maxStr = maxTokens
    ? `${Number(maxTokens).toLocaleString()} tokens`
    : 'auto-detect (ccusage) — run with --max <tokens> if not installed';

  return [
    '============================================================',
    `  PGE Usage Guard — ENABLED`,
    `  Threshold : ${threshold}% of ${type} limit`,
    `  Max tokens: ${maxStr}`,
    `  Config    : ${LIMIT_CONFIG_PATH}`,
    '',
    `  The pipeline will pause at the next phase boundary when`,
    `  usage reaches ${threshold}%. Resume after limit resets:`,
    `  → pge --resume`,
    '============================================================',
  ].join('\n');
}

function clearLimit() {
  try { fs.unlinkSync(LIMIT_CONFIG_PATH); } catch {}
  try {
    const pid = Number(fs.readFileSync(GUARD_PID_FILE, 'utf8').trim());
    if (pid) process.kill(pid, 'SIGTERM');
  } catch {}
  try { fs.unlinkSync(GUARD_PID_FILE); } catch {}
  return 'PGE Usage Guard disabled. No limit threshold is active.';
}

function limitStatus() {
  try {
    const cfg = JSON.parse(fs.readFileSync(LIMIT_CONFIG_PATH, 'utf8'));
    const maxStr = cfg.maxTokens
      ? `${Number(cfg.maxTokens).toLocaleString()} tokens`
      : 'auto-detect (ccusage)';
    return [
      `PGE Usage Guard: ${cfg.enabled ? 'ENABLED' : 'DISABLED'}`,
      `  Threshold : ${cfg.threshold}%`,
      `  Window    : ${cfg.type || '5h'}`,
      `  Max tokens: ${maxStr}`,
      `  Set at    : ${cfg.setAt || 'unknown'}`,
    ].join('\n');
  } catch {
    return 'PGE Usage Guard: DISABLED (no config found).\nUse /pge-limit <percentage> to enable.';
  }
}

// ── MCP tools list ────────────────────────────────────────────────────────────
const TOOLS = [
  { name: 'pge_status',          description: 'Show PGE installation status, auto-launch, and status-line state.' },
  { name: 'pge_update',          description: 'Update PGE: git pull + reinstall all skills and agents.' },
  { name: 'pge_autolaunch_on',   description: 'Enable auto-launch: opens indicator terminal when /pge is invoked.' },
  { name: 'pge_autolaunch_off',  description: 'Disable auto-launch.' },
  { name: 'pge_statusline_on',   description: 'Add PGE state to the Claude Code status bar.' },
  { name: 'pge_statusline_off',  description: 'Remove PGE state from the Claude Code status bar.' },
  { name: 'pge_preflight',       description: 'Run pre-flight check (Playwright MCP, git, agents, skills). Pass cwd in input.' },
  { name: 'pge_clean',           description: 'Delete pge-workspace/ in the current project. Pass cwd in input.' },
  { name: 'pge_summary',         description: 'Show sprint-by-sprint results summary. Pass cwd in input.' },
  { name: 'pge_indicator',       description: 'Open a live agent indicator in a new Terminal window. Pass cwd in input.' },
  { name: 'pge_notify',          description: 'Start macOS notification watcher in background. Pass cwd in input.' },
  {
    name: 'pge_eval_backend',
    description: 'Get or set the evaluator backend (claude/codex/gemini) for PGE pipelines. claude=full Playwright; codex/gemini=static code review via tmux.',
    inputSchema: {
      type: 'object',
      properties: {
        action:  { type: 'string', enum: ['show', 'set', 'clear'], description: 'show=display current; set=write config; clear=remove project override' },
        backend: { type: 'string', enum: ['claude', 'codex', 'gemini'], description: 'Backend to set (required when action=set)' },
        global:  { type: 'boolean', description: 'If true, writes to global ~/.claude/pge-eval-backend instead of project-level' },
        cwd:     { type: 'string',  description: 'Project directory (optional)' },
      },
      required: [],
    },
  },
  {
    name: 'pge_set_limit',
    description: 'Enable the PGE usage guard. Saves a threshold config and starts the background monitor.',
    inputSchema: {
      type: 'object',
      properties: {
        threshold : { type: 'number',  description: 'Pause at this % of the usage limit (1–99)' },
        type      : { type: 'string',  enum: ['5h', 'weekly'], description: 'Time window (default: 5h)' },
        maxTokens : { type: 'number',  description: 'Your plan\'s max tokens per window (optional — falls back to ccusage)' },
        cwd       : { type: 'string',  description: 'Project directory (optional)' },
      },
      required: ['threshold'],
    },
  },
  {
    name: 'pge_clear_limit',
    description: 'Disable the PGE usage guard and remove the threshold config.',
    inputSchema: { type: 'object', properties: {}, required: [] },
  },
  {
    name: 'pge_limit_status',
    description: 'Show current PGE usage guard configuration.',
    inputSchema: { type: 'object', properties: {}, required: [] },
  },
].map((t, i, arr) => {
  // These tools already have their own inputSchema
  if (['pge_eval_backend', 'pge_set_limit', 'pge_clear_limit', 'pge_limit_status'].includes(t.name)) return t;
  return { ...t, inputSchema: { type: 'object', properties: { cwd: { type: 'string', description: 'Project directory (optional, defaults to current)' } }, required: [] } };
});

// ── MCP server ────────────────────────────────────────────────────────────────
function send(obj) { process.stdout.write(JSON.stringify(obj) + '\n'); }

const rl = readline.createInterface({ input: process.stdin, terminal: false });

rl.on('line', (line) => {
  let msg;
  try { msg = JSON.parse(line.trim()); } catch { return; }
  if (!msg || msg.jsonrpc !== '2.0') return;

  const { id, method } = msg;

  if (method === 'initialize') {
    try { install(); } catch {}
    send({ jsonrpc: '2.0', id, result: { protocolVersion: '2024-11-05', capabilities: { tools: {} }, serverInfo: { name: 'pge-orchestrator', version: '2.7.0' } } });

  } else if (method === 'notifications/initialized') {
    // no response

  } else if (method === 'tools/list') {
    send({ jsonrpc: '2.0', id, result: { tools: TOOLS } });

  } else if (method === 'tools/call') {
    const name = msg.params?.name;
    const cwd  = msg.params?.arguments?.cwd;
    let text;
    try {
      if      (name === 'pge_status')         text = status();
      else if (name === 'pge_update')         text = update();
      else if (name === 'pge_autolaunch_on')  text = autolaunchOn();
      else if (name === 'pge_autolaunch_off') text = autolaunchOff();
      else if (name === 'pge_statusline_on')  text = statuslineOn();
      else if (name === 'pge_statusline_off') text = statuslineOff();
      else if (name === 'pge_preflight')      text = preflight(cwd);
      else if (name === 'pge_clean')          text = clean(cwd);
      else if (name === 'pge_summary')        text = summary(cwd);
      else if (name === 'pge_indicator')      text = openIndicator(cwd);
      else if (name === 'pge_notify')         text = startNotify(cwd);
      else if (name === 'pge_eval_backend') {
        const action  = msg.params?.arguments?.action  || 'show';
        const backend = msg.params?.arguments?.backend;
        const global  = msg.params?.arguments?.global  || false;
        text = evalBackend(action, backend, global, cwd);
      }
      else if (name === 'pge_set_limit')    text = setLimit(msg.params?.arguments || {});
      else if (name === 'pge_clear_limit')  text = clearLimit();
      else if (name === 'pge_limit_status') text = limitStatus();
      else text = `Unknown tool: ${name}`;
    } catch (e) { text = `Error: ${e.message}`; }
    send({ jsonrpc: '2.0', id, result: { content: [{ type: 'text', text }] } });

  } else if (id !== undefined) {
    send({ jsonrpc: '2.0', id, result: {} });
  }
});
